### ISSUE TITLE
keypatch.py: ERROR: fail to load the dynamic library.

### ISSUE THREAD

**Issue by theqlabs** [keystone-engine/keypatch#11]
Hi y'all, trying to install keypatch on `Ubuntu 16.04.1 LTS`: 

Followed the [instructions](http://www.keystone-engine.org/keypatch/#appendix-install-keystone-for-ida-pro) but can't get IDA to load the `keypatch` plugin successfully.

First error I get when starting `IDA 6.95` is:

`keypatch.py: ERROR: fail to load the dynamic library.`
and
`keypatch.py: cannot import name arm_const`

even though: 

`xxx@xxx:/opt/ida-6.95/python/lib/python2.7/dist-packages/keystone`
`-rwxr-xr-x 1 root root 6497308 Aug 31 22:38 libkeystone.so.0`

help appreciated!

**Comment by aquynh** [comment]
is this the output if you enter "import keystone" at the Python prompt inside IDA?

**Comment by aquynh** [comment]
see related issue with solution: https://github.com/keystone-engine/keypatch/issues/12

**Comment by theqlabs** [comment]
I'm aware of [#12](https://github.com/keystone-engine/keypatch/issues/12) but I do not get the same error from python prompt inside IDA, I get:

`ImportError: cannot import name arm_const`

which makes me think it actually can't load libkeystone.so. 

Also I didn't use `pip` at all, built keystone using `./make-share.sh lib32 lib-only` after building on my system normally.

**Comment by aquynh** [comment]
@pedrib, do you have any comments on this issue?

**Comment by aquynh** [comment]
@theqlabs, have you solved this issue yet? we updated the instructions at http://www.keystone-engine.org/keypatch/#appendix-install-keystone-for-ida-pro, that may help you.

**Comment by pedrib** [comment]
Sorry no idea about this. Are you on Linux 64 bit, and have you followed the updated readme?

**Comment by theqlabs** [comment]
So I've gotten a bit further by ensuring IDA is using a 32-bit Python runtime and installing Keystone-Engine through the 32-bit Python PIP. But as I load Keypatch, I'm not getting the following:

```
keypatch.py: name 'KS_ARCH_X86' is not defined
Traceback (most recent call last):
  File "/opt/ida-6.95/python/ida_idaapi.py", line 509, in IDAPython_ExecScript
    execfile(script, g)
  File "/opt/ida-6.95/plugins/keypatch.py", line 111, in <module>
    class Keypatch_Asm:
  File "/opt/ida-6.95/plugins/keypatch.py", line 114, in Keypatch_Asm
    "X86 16-bit": (KS_ARCH_X86, KS_MODE_16),                # X86 16-bit
NameError: name 'KS_ARCH_X86' is not defined
```

Thoughts?

**Comment by aquynh** [comment]
no, i think you copied Python binding of Keystone to the wrong place. that is why IDA still cannot find Keystone Python binding.

can you copy the whole directory `bindings/python/` in Keystone source code (from 
https://github.com/keystone-engine/keystone/tree/master/bindings/python) to `/opt/ida-6.95/python/`, so that you have `/opt/ida-6.95/python/keystone/` after that?

then, copy all the (32bit version) `libkeystone.so*` to `/opt/ida-6.95/python/keystone/`, and reload IDA to see all the problems are gone.

**Comment by theqlabs** [comment]
**I am an idiot who can not follow directions.**

Thanks y'all, I tried to do something clever by installing a 32-bit pip with a separate 32-bit python runtime and it was ruining the process that y'all actually recommended, which works. Apologies! <3
