### ISSUE TITLE
No module named 'keystone' on OSX

### ISSUE THREAD

**Issue by 0xmilkmix** [keystone-engine/keypatch#12]
Hello,

Installed keystone engine using pip and everything is working fine from python (no venv here). However, IDA (6.95.160808 (64-bit or 32-bit)) cannot find the module.

Probably a symlink problem...

Thanks!

**Comment by aquynh** [comment]
at the Python prompt inside IDA, if you enter "import keystone", what is the output?

**Comment by 0xmilkmix** [comment]
only: "ImportError: No module named keystone" in the two versions of IDA

**Comment by aquynh** [comment]
the reason is that IDA cannot find the Python binding of Keystone at the standard path.

can you do this to copy the whole Python binding directory of Keystone to IDA, then try again? (replace `6.8` with your actual IDA version)

    $ git clone https://github.com/keystone-engine/keystone.git
    $ cd keystone
    $ sudo cp -r bindings/python/keystone /Applications/IDA\ Pro\ 6.8/idaq.app/Contents/MacOS/python

**Comment by 0xmilkmix** [comment]
working that way, thanks!

**Comment by aquynh** [comment]
great!

btw, you can use the latest keypatch.py from Github, which fixes some important bugs in v1.0, and offers many new features.

**Comment by fenderluvr** [comment]
@aquynh What does this line do on MAC OS? 

$ sudo cp -r bindings/python/keystone /Applications/IDA\ Pro\ 6.8/idaq.app/Contents/MacOS/python

I have the same issue on windows 10 and would like to resolve.
