### ISSUE TITLE
Linux 64bit, incorrect name of the keystone lib in keystone folder

### ISSUE THREAD

**Issue by dummys** [keystone-engine/keypatch#20]
Hi,
After digging around I found the bug for the "Fail to load the dynamic library.
Stracing IDA shows that it search for a _libkeystone.so_ and not a _libkeystone.so.0_.
Also in your documentation under linux it's not working if you copy the keystone folder in ida-xx/python.
We must copy it to _/opt/ida-xxx/python/lib/python2.7_.
Then renaming the lib did the tricks.

> Loading processor module /opt/ida-6.95/procs/arm.ilx for ARM...OK
> keypatch.py: ERROR: fail to load the dynamic library.
> Traceback (most recent call last):
>   File "/opt/ida-6.95/python/ida_idaapi.py", line 509, in IDAPython_ExecScript
>     execfile(script, g)
>   File "/opt/ida-6.95/plugins/keypatch.py", line 23, in <module>
>     from keystone import *
>   File "/opt/ida-6.95/python/lib/python2.7/keystone/__init__.py", line 4, in <module>
>     from .keystone import Ks, ks_version, ks_arch_supported, version_bind, debug, KsError, __version__
>   File "/opt/ida-6.95/python/lib/python2.7/keystone/keystone.py", line 74, in <module>
>     raise ImportError("ERROR: fail to load the dynamic library.")
> ImportError: ERROR: fail to load the dynamic library.

**Comment by aquynh** [comment]
if you follow the instructions of building Keystone, you would have `libkeystone.so.0` & `libkeystone.so`, both under `build/llvm/lib`, in which `libkeystone.so` links to `libkeystone.so.0`.

then if you copy both of them to IDA directory as in instruction, IDA would be able to find `libkeystone.so`.

so i think our documentation is fine.

**Comment by dummys** [comment]
ok my bad, you right. Thanks
