### ISSUE TITLE
About endian switch bug on arm ins assembly

### ISSUE THREAD

**Issue by Ja5h0n** [keystone-engine/keypatch#23]
Details
Recently，as a software reverse newbee. I’m try to crack a Ali crackme.apk(attachment).
Find the check func is in Android Native Code .So I use IDA Pro to dynamic debugging, find anti-debug method. I need to Turn around this ，I need to alter the memory and didn't find the function in IDA like OllyDBG to alter binary code by alter ASM sentences.  So I’d
like to appreciate to god that I find. the great works you have built ,And I find some problems(big endian and little endian’ switch) as I twitter U. 
 
![image](https://user-images.githubusercontent.com/28643036/27759333-d4f0707c-5e60-11e7-8eac-a244517acc38.png)

A little Suggestion
If this is my project , I would like to switch endian Mode can be choose by user. If occur a error，it can be corrected manually.

THX
[TwitterFromDelphicGeek.zip](https://github.com/keystone-engine/keypatch/files/1116872/TwitterFromDelphicGeek.zip)

**Comment by aquynh** [comment]
i am looking at your **libcrackme.so**, but this is detected as **little endian** file, not **big endian** file?

**Comment by aquynh** [comment]
btw, make sure you are using the latest version Keypatch 2.1. you can verify version from menu Right-click -> Keypatch -> About.

**Comment by Ja5h0n** [comment]
Version is the lastest ,and the ida pro version is
![image](https://user-images.githubusercontent.com/28643036/27762203-09188080-5ea0-11e7-9663-6230b8e13334.png)
![image](https://user-images.githubusercontent.com/28643036/27762226-759e2cb4-5ea0-11e7-8606-a17f3985f135.png)
 Indeed this is little endian  but keypatch can't select the little endian mode . what can I do  to fix it?

**Comment by Ja5h0n** [comment]
I used my classmates pc  win7 x64 no python3  is seems no problem. my platform is win 10  both install python2.7 and python 3.6  is that have some sides effect？

**Comment by aquynh** [comment]
no, IDA uses its internal Python, which is Python 2.7.

so this is not really a bug?

you should find a big-endian binary, and attach here, so i can confirm.

**Comment by Ja5h0n** [comment]
Here is my Test Result，and test examples，I test two platforms and find diffences between WIn7 and WIn10, it seems occur this problem  in diffent way. Check it . finally thx for ur patient~
[Desktop.zip](https://github.com/keystone-engine/keypatch/files/1117163/Desktop.zip)

**Comment by aquynh** [comment]
fixed now, please confirm it works for you.

you just need to get the latest https://github.com/keystone-engine/keypatch/blob/master/keypatch.py from Github, then overwrites your keypatch.py in your plugin directory, then restart IDA.

**Comment by Ja5h0n** [comment]
It works！！！Thx，you Really did a great works. Actually, I really enjoy the process communicate with you :-)   
(pls ignore my poor English expression ability)

**Comment by aquynh** [comment]
Great! Then give this Github repo a star if you haven't done that :-)

**Comment by Ja5h0n** [comment]
Absolutely，enjoy ur weekend.
