### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by securisec** [keystone-engine/keypatch#28]
Followed the instructions on a Mac with the latest IDA 7, but getting an ImportError.
keypatch.py: cannot import name arm_const

Any suggestions?

**Comment by aquynh** [comment]
did you follow every steps properly, from section 2: http://www.keystone-engine.org/keypatch/?

**Comment by securisec** [comment]
Yes. Installed keystone via pip, copied keystone site packages dir to /Applications/IDA 7.0... /python dir. Saved keypatch.py in same dir but in the plugin folder. Here is the exact error

`/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/keypatch.py: cannot import name arm_const
Traceback (most recent call last):
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/ida_idaapi.py", line 553, in IDAPython_ExecScript
    execfile(script, g)
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/keypatch.py", line 22, in <module>
    from keystone import *
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/keystone/__init__.py", line 2, in <module>
    from . import arm_const, arm64_const, mips_const, sparc_const, hexagon_const, systemz_const, ppc_const, x86_const
ImportError: cannot import name arm_const`

**Comment by fjh658** [comment]
sudo pip install keystone-engine error occured？
Do you have cmake in macOS？@securisec

**Comment by securisec** [comment]
@fjh658 no issues/errors installing keystone-engine using pip. cmake already installed in macOS

**Comment by fjh658** [comment]
print sys.path in python console of ida？
check python environment

**Comment by fjh658** [comment]
Quick start
Steps:
1. install brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

2. brew install cmake

3. sudo pip install keystone-engine
Default install path: /Library/Python/2.7/site-packages/keystone
Dir structure:
![image](https://user-images.githubusercontent.com/5550316/30952983-ae2c0608-a45c-11e7-8139-5288e46670d4.png)

Check Method:
1. print sys.path in python console of ida
2. check python environment about the dir of keystone.

@securisec

**Comment by securisec** [comment]
Thanks @fjh658 ! steps 1-3 were already done on my Mac. Because I use brew python, my keystone was installed in `/usr/local/lib/python2.7/site-packages/keystone`. contents of that folder is 
![image](https://user-images.githubusercontent.com/22226823/30969855-97a91464-a431-11e7-8bcd-816e88e4bdf3.png)

then i used 
`cp -r /usr/local/lib/python2.7/site-packages/keystone /Applications/IDA\ Pro\ 7.0/idaq.app/Contents/MacOS/python` to copy keystone into ida python. 

The error is not triggering because keystone is getting an import error. according to ida logs, the error is at `/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/keypatch.py: cannot import name arm_const`

![image](https://user-images.githubusercontent.com/22226823/30969988-fd3af018-a431-11e7-84ba-0872f7638489.png)

Thanks!

**Comment by fjh658** [comment]
You enter this in the console of ida

```python
Python>print keystone
<module 'keystone.keystone' from '/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/keystone/keystone.py'>

Python>print keystone.arm_const
<module 'keystone.arm_const' from '/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/keystone/arm_const.py'>
```
and

enter this in the  python standard console
```python
Python 2.7.13 (default, Jul 18 2017, 09:17:00)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keystone
>>> print keystone
<module 'keystone' from '/usr/local/lib/python2.7/site-packages/keystone/__init__.pyc'>
>>> print keystone.arm_const
<module 'keystone.arm_const' from '/usr/local/lib/python2.7/site-packages/keystone/arm_const.pyc'>
>>>
``` 

compare


@securisec

**Comment by securisec** [comment]
thanks. print keystone in python produces a `ImportError: ERROR: fail to load the dynamic library.`

inside ida, it produces a `NameError: name 'keystone' is not defined`

**Comment by fjh658** [comment]
This is key info.
ImportError: ERROR: fail to load the dynamic library

![image](https://user-images.githubusercontent.com/5550316/30997551-3bde6be0-a48e-11e7-9813-3b196548f9a7.png)

You did not successfully generate the "libkeystone.dylib"

**Comment by securisec** [comment]
![image](https://user-images.githubusercontent.com/22226823/30997717-c5534176-a497-11e7-8b6b-ee5427020ed2.png)

it seems that i am installing keystone fine, but still not installing it properly. do you suggest a different way to install it? cmake is already installed so i am not sure where it is going wrong.

**Comment by fjh658** [comment]
1. Download keystone-engine, and extract this.
```
https://pypi.python.org/packages/9a/fc/ed0d3f46921bfaa612d9e8ce8313f99f4149ecf6635659510220c994cb72/keystone-engine-0.9.1-3.tar.gz
```
2. Manual compile and install keystone-engine, see this log completely.
```
cd keystone-engine-0.9.1-3
sudo python setup.py install
```

**Comment by securisec** [comment]
Perfect! Now it is working! thank you so much for your help!

**Comment by aquynh** [comment]
Great! Please consider sending pull req to improve this install section with more details, so others can benefit from your experience.

Thanks

**Comment by peshi** [comment]
This is how far I came with Keypatch after compiling with cmake.
Plugin seems to load when checking 'print keystone' etc.

Failed while executing plugin_t.init():
Traceback (most recent call last):
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/keypatch.py", line 1499, in init
    menu = idaapi.add_menu_item("Edit/Keypatch/", "Patcher     (Ctrl-Alt-K)", "", 1, self.patcher, None)
AttributeError: 'module' object has no attribute 'add_menu_item'

**Comment by thonsun** [comment]
It will waste your time to read it ,no solve for this problem

**Comment by Q1IQ** [comment]
Finally we need to copy the folder keystone to IDA.app by this: 
`
appledeMacBook-Pro-2:site-packages apple$ sudo cp -r ./keystone /Applications/IDA\ Pro\ 7.0/ida64.app/Contents/MacOS/python
appledeMacBook-Pro-2:site-packages apple$ sudo cp -r ./keystone /Applications/IDA\ Pro\ 7.0/ida64.app/Contents/MacOS/python
appledeMacBook-Pro-2:site-packages apple$ pwd
/usr/local/lib/python2.7/site-packages
`
And my environment is macOS , my python is like this:
`
Python 2.7.16 (default, Jun 19 2019, 07:41:28) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keystone
>>> print keystone
<module 'keystone' from '/usr/local/lib/python2.7/site-packages/keystone/__init__.pyc'>
>>> print keystone.arm_const
<module 'keystone.arm_const' from '/usr/local/lib/python2.7/site-packages/keystone/arm_const.pyc'>
`
