### ISSUE TITLE
Update appendix for IDA 7.0

### ISSUE THREAD

**Issue by SilverBut** [keystone-engine/keypatch#29]
IDA 7.0 is now a native x64 application, which means it is now using Python 2.7 x64. So it would be great if we can update the appendix.

**Comment by aquynh** [comment]
that is right. would you send a pull req to update the docs?

**Comment by SilverBut** [comment]
Pull request.....good idea but I'm wondering if my install method can be applied to other people.

I've also noticed a pull request also about this issue. Will check and try..

**Comment by SilverBut** [comment]
Pushed pr #31

**Comment by o0xmuhe** [comment]
I have tested on my mac with IDA Pro7.0 . You  need to build keystone and install the bindings on your computer,then copy keypatch.py to IDA_PWD/IDA Pro 7.0/ida.app/Contents/MacOS/plugins .
After all,it works.

**Comment by fjh658** [comment]
@o0xmuhe
  
https://github.com/keystone-engine/keypatch/issues/28

check methods:

You enter this inside the python console of ida
```
Python>print keystone
<module 'keystone.keystone' from '/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/keystone/keystone.py'>

Python>print keystone.arm_const
<module 'keystone.arm_const' from '/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/keystone/arm_const.py'>
```
and

enter this in the python standard console
```
Python 2.7.13 (default, Jul 18 2017, 09:17:00)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keystone
>>> print keystone
<module 'keystone' from '/usr/local/lib/python2.7/site-packages/keystone/__init__.pyc'>
>>> print keystone.arm_const
<module 'keystone.arm_const' from '/usr/local/lib/python2.7/site-packages/keystone/arm_const.pyc'>
>>>
```
compare

**Comment by o0xmuhe** [comment]
@fjh658  I don't konw why they are the same on my mac.May be sth wrong...

**Comment by fjh658** [comment]
Please selected the assembly instructions and try again. @o0xmuhe

**Comment by o0xmuhe** [comment]
It works in my way. :)

**Comment by SilverBut** [comment]
Seems no more questions about the appendix. Close now.
