### ISSUE TITLE
Patcher menu broken on IDA 7.2

### ISSUE THREAD

**Issue by sinaelgl** [keystone-engine/keypatch#58]
Since IDA 7.2 beta (and including the final release), the Patcher menu no longer works. Instead, the following is presented to the user:
![key](https://user-images.githubusercontent.com/4005050/48058021-1eb4c780-e1be-11e8-8c0d-14ca7dcc66d4.png)

**Comment by fjh658** [comment]
https://github.com/fjh658/keystone-engine

`Supported IDA 7.2 release version`  
https://github.com/fjh658/keypatch     @sinaelgl

**Comment by confilemg** [comment]
I have the same problem. The plugin does not work with IDA 7.2.

**Comment by fjh658** [comment]
The official update version may not be very timely, you can modify it yourself.
So easy.
https://github.com/fjh658/keypatch/commit/4321f9820db006c4d91ec5876f58a2b0de4d16a2#diff-c583c92cf49e3f4fcbd569bbf67bd5e7 @confilemg

**Comment by confilemg** [comment]
Yes that fixes the problem. Thank you.

**Comment by pedrib** [comment]
@fjh658 yes that works! Can you please make a pull request to the main keypatch repo?

**Comment by fjh658** [comment]
> @fjh658 yes that works! Can you please make a pull request to the main keypatch repo?

Merged.
