### ISSUE TITLE
arm patch error

### ISSUE THREAD

**Issue by a1rsupp1y** [keystone-engine/keypatch#6]
Keypatch: attempt to modify "SUB SP, SP, #8" at 0xB618 to "SUB SP, SP, #0xc"
Keypatch: successfully patched 4 byte(s) at 0xB618 from [82 B0 19 A9] to [0C D0 4D E2]
this should be  from [82 B0 19 A9] to [83 B0 19 A9].

**Comment by aquynh** [comment]
do you mean the log info is wrong, or also the patching is wrong?

**Comment by a1rsupp1y** [comment]
also the patching  is wrong too

**Comment by redragonvn** [comment]
I've fixed this issue. Please checkout the latest code.

**Comment by a1rsupp1y** [comment]
good job

**Comment by aquynh** [comment]
close, thanks.
