### ISSUE TITLE
FAILED to process this input

### ISSUE THREAD

**Issue by shoaloak** [keystone-engine/keypatch#61]
I use IDA 7.0.170914 on Windows 10 x64 with Keypatch v2.2.
When i try to patch instructions, I always get the "FAILED to process this input" error.

`Keypatch: attempting to fill range [0x100DE6:0x100DE5] with "mov eax, 42"`
`Keypatch: successfully filled range [0x100DE6:0x100DE5] (0 bytes) with "mov eax, 42", replaced ""`
`Keypatch: FAILED to process this input 'mov eax, 42'`
`Keypatch: successfully reverted 0 byte(s) at 0x100DE6 from [] to []`

**Comment by Animelubitel** [comment]
Right click on a line, but not select it

**Comment by shoaloak** [comment]
Too long ago, already got it working on Wine.
Closing.
