### ISSUE TITLE
port it to ida 7.4 and python3

### ISSUE THREAD

**Issue by dummys** [keystone-engine/keypatch#65]
Hi,

Is it possible to port it to ida 7.4 please ?

**Comment by liuxuan30** [comment]
+1. Since py2.7 is deprecating soon, I hope keypatch could support Python 3

**Comment by aquynh** [comment]
The latest code in github should work in Python3

**Comment by liuxuan30** [comment]
@aquynh I tried latest master's keypatch.py on IDA 7.4 python 3:
```
/Applications/IDA Pro 7.4/ida64.app/Contents/MacOS/plugins/keypatch.py: invalid syntax (keypatch.py, line 7)
Traceback (most recent call last):
  File "/Applications/IDA Pro 7.4/ida64.app/Contents/MacOS/python/3/ida_idaapi.py", line 589, in IDAPython_ExecScript
    code = compile(fin.read(), script, 'exec')
  File "/Applications/IDA Pro 7.4/ida64.app/Contents/MacOS/plugins/keypatch.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```
It seems the master branch didn't support yet.

**Comment by liuxuan30** [comment]
@aquynh I tried latest master keypatch.py on IDA 7.4 with python3:
```
/Applications/IDA Pro 7.4/ida64.app/Contents/MacOS/plugins/keypatch.py: invalid syntax (keypatch.py, line 131)
Traceback (most recent call last):
  File "/Applications/IDA Pro 7.4/ida64.app/Contents/MacOS/python/3/ida_idaapi.py", line 589, in IDAPython_ExecScript
    code = compile(fin.read(), script, 'exec')
  File "/Applications/IDA Pro 7.4/ida64.app/Contents/MacOS/plugins/keypatch.py", line 131
    except HTTPError, e:
                    ^
SyntaxError: invalid syntax
```
it seems not supported yet.

**Comment by s3c** [comment]
Updating the exception handlers was easy enough, but you manually have to install keystone, which then fails to include some IDC functions, presumably because they aren't in the API anymore. Didn't look into this further.

**Comment by kiritowch** [comment]
Looking forward to

**Comment by Moojx** [comment]
> @aquynh I tried latest master keypatch.py on IDA 7.4 with python3:
> 
> ```
> /Applications/IDA Pro 7.4/ida64.app/Contents/MacOS/plugins/keypatch.py: invalid syntax (keypatch.py, line 131)
> Traceback (most recent call last):
>   File "/Applications/IDA Pro 7.4/ida64.app/Contents/MacOS/python/3/ida_idaapi.py", line 589, in IDAPython_ExecScript
>     code = compile(fin.read(), script, 'exec')
>   File "/Applications/IDA Pro 7.4/ida64.app/Contents/MacOS/plugins/keypatch.py", line 131
>     except HTTPError, e:
>                     ^
> SyntaxError: invalid syntax
> ```
> 
> it seems not supported yet.


> @aquynh I tried latest master keypatch.py on IDA 7.4 with python3:
> 
> ```
> /Applications/IDA Pro 7.4/ida64.app/Contents/MacOS/plugins/keypatch.py: invalid syntax (keypatch.py, line 131)
> Traceback (most recent call last):
>   File "/Applications/IDA Pro 7.4/ida64.app/Contents/MacOS/python/3/ida_idaapi.py", line 589, in IDAPython_ExecScript
>     code = compile(fin.read(), script, 'exec')
>   File "/Applications/IDA Pro 7.4/ida64.app/Contents/MacOS/plugins/keypatch.py", line 131
>     except HTTPError, e:
>                     ^
> SyntaxError: invalid syntax
> ```
> 
> it seems not supported yet.


Is it solved？

**Comment by fuomag9** [comment]
@Moojx 593fcacb3022d9fbd510bbb49297008b712f1ec7 works for me

**Comment by xiaoye-2018** [comment]
this exception code is adapt to python 2.x,  you only to update relevant exception code

**Comment by kiritowch** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
