### ISSUE TITLE
Keypatch Syntax Error: Invalid Syntax. Line 97. On IDA Pro 7.5 SP3(Version 7.5.201028)

### ISSUE THREAD

**Issue by LoadCursor** [keystone-engine/keypatch#78]
https://user-images.githubusercontent.com/68258337/103153911-19b49700-47cf-11eb-899a-462b247fd894.mp4

When I open IDA PRO 7.5 SP3, keypatch says the error shown in the video. But keystone-engine is correctly installed, I believe. And I installed Python 2.7.18, Python 3.8.6 to support IDA Pro and Keypatch. Thank you for reading this feedback!

**Comment by eblue3** [comment]
@LoadCursor Just change the:
except HTTPError, e:
=> except HTTPError as e:

There'll be plenty of that syntax error in this keypatch. I have done replace them ", e" to "as e" and it works normally.

**Comment by eblue3** [comment]
> 
> bandicam.2020-12-26.23-05-58-464.mp4
> 
> When I open IDA PRO 7.5 SP3, keypatch says the error shown in the video. But keystone-engine is correctly installed, I believe. And I installed Python 2.7.18, Python 3.8.6 to support IDA Pro and Keypatch. Thank you for reading this feedback!

@LoadCursor Just change the:
except HTTPError, e:
=> except HTTPError as e:

There'll be plenty of that syntax error in this keypatch. I have done replace them ", e" to "as e" and it works normally.

**Comment by y0ush4** [comment]
you mean ",e" to "e"??

**Comment by y0ush4** [comment]
> 
> 
> > bandicam.2020-12-26.23-05-58-464.mp4
> > When I open IDA PRO 7.5 SP3, keypatch says the error shown in the video. But keystone-engine is correctly installed, I believe. And I installed Python 2.7.18, Python 3.8.6 to support IDA Pro and Keypatch. Thank you for reading this feedback!
> 
> @LoadCursor Just change the:
> except HTTPError, e:
> => except HTTPError as e:
> 
> There'll be plenty of that syntax error in this keypatch. I have done replace them ", e" to "as e" and it works normally.

you mean ",e" to "e"??

**Comment by Fallen1997** [comment]
> > bandicam.2020-12-26.23-05-58-464.mp4
> > When I open IDA PRO 7.5 SP3, keypatch says the error shown in the video. But keystone-engine is correctly installed, I believe. And I installed Python 2.7.18, Python 3.8.6 to support IDA Pro and Keypatch. Thank you for reading this feedback!
> 
> @LoadCursor Just change the:
> except HTTPError, e:
> => except HTTPError as e:
> 
> There'll be plenty of that syntax error in this keypatch. I have done replace them ", e" to "as e" and it works normally.



After replacing ", e" with "as e"

im getting another error. Im using IDA pro 7.5
i really need help, i can't fix it.


E:\Hex\plugins\keypatch.py: module 'idaapi' has no attribute 'Choose2'
Traceback (most recent call last):
  File "E:\Hex\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "E:/Hex/plugins/keypatch.py", line 1134, in <module>
    class SearchResultChooser(idaapi.Choose2):
AttributeError: module 'idaapi' has no attribute 'Choose2'

**Comment by LoadCursor** [comment]
@y0ush4 @eblue3 Much obliged!!! Problem solved! Sorry for the late message, I've had a little problem on account verification.

**Comment by eblue3** [comment]
> 
> 
> > > bandicam.2020-12-26.23-05-58-464.mp4
> > > When I open IDA PRO 7.5 SP3, keypatch says the error shown in the video. But keystone-engine is correctly installed, I believe. And I installed Python 2.7.18, Python 3.8.6 to support IDA Pro and Keypatch. Thank you for reading this feedback!
> > 
> > 
> > @LoadCursor Just change the:
> > except HTTPError, e:
> > => except HTTPError as e:
> > There'll be plenty of that syntax error in this keypatch. I have done replace them ", e" to "as e" and it works normally.
> 
> you mean ",e" to "e"??
> 
> if yes its still not solved i have 7.5 and python 3.9.5 the error is
> 
> Autoanalysis subsystem has been initialized.
> C:\IDA Pro 7.5\plugins\keypatch.py: No module named 'keystone'
> Traceback (most recent call last):
> File "C:\IDA Pro 7.5\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
> exec(code, g)
> File "C:/IDA Pro 7.5/plugins/keypatch.py", line 53, in
> from keystone import *
> ModuleNotFoundError: No module named 'keystone'

"ModuleNotFoundError: No module named 'keystone'" means you didn't install the package.
Try this on shell: pip install keystone-engine
Or you can google yourself to find out which package you're missing on python.
