### ISSUE TITLE
Install issue on MacOS IDA

### ISSUE THREAD

**Issue by OtterV** [keystone-engine/keypatch#92]
Have tried many solution but failed.
1. Have checked python_path(terminal & IDA use the same) & sys.path in IDA(7.7) & cmake, everything right.
2. Try:
    a. `sudo pip install keystone-engine` 
         didn't generate libkeystone.dylib.
    b. download & `sudo python setup.py install` 
        when use python in local terminal, `from keystone import *` succeed. 
        However, in IDA, `ImportError: ERROR: fail to load the dynamic library.` 
        And to find the reason, I modify the keystone.py to find the reason. When load libkeystone.dylib, it raise `(mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')` 
    c. Then I tried `../make-share.sh macos-universal lib_only` , raise error `ld: symbol(s) not found for architecture i386`
I would be very grateful if someone could give me some advice.

**Comment by masagrator** [comment]
"ImportError: ERROR: fail to load the dynamic library." - I think this is because you don't have Python 3 installed. From some revision of IDA 7.x Python 2 is not supported. 

Even though readme mentions Python 2, actually it works with Python 3 too.

**Comment by callengre** [comment]
pip install will archieve， not use  dylib。 
platform macOS 13.3
ida version， 9.0
refer
https://bbs.kanxue.com/thread-282933.htm

**Comment by OtterV** [comment]
Thanks!

**Comment by OtterV** [comment]
Thanks for answer!

When I use pip, I just couldn‘t generate dylib; pip way also should generate dylib to use.

I have solved my problem by modifying `make_common.sh` in keystone source ( deleted `i386` ), because platform don't support 32bits.

After this, I solved next new problem by @callengre's answer, update keypatch.py file.
